= 1.WSO2 Enterprise Mobility Manager (EMM)

* WSO2 Enterprise Mobility Manager (EMM) pricing is typically based on a subscription model, where costs depend on factors such as the number of devices to be managed,

= 2.Kandji

* 21-day free trial. No credit card required.

= 3.Miradore

* Includes a free 14-day trial
* Also a free plan that can manage up to 50 devices BUT with limited features that do not MEET our GOALS :( !

= 4.Scalefusion MDM

* 14 Day Free Trial. No Credit Card required.

= 5.ManageEngine MDM

* START YOUR 30-DAY FREE TRIAL

= 6.Flyve MDM

* For the moment, the Flyve MDM project is therefore archived (on Github https://github.com/flyve-mdm/).

= 7. jamf

* Jamf is a paid solution, and the pricing is generally based on the number of devices managed, along with the specific plan you choose. While it offers powerful features for - Apple devices, it is not free.

= 8. SimpleMDM

* We do not support Android, Windows, or any other non-Apple device platforms.

= 9.  Hexnode

* Try Hexnode free for 14 days

= 10. NinjaOne

* Start a Free Trial

= 11. Baramundi
 * Get a free trial or personalized demo

= 12. Rippling

* Rippling offers a subscription-based pricing model, and the cost is generally based on the number of devices being managed, as well as the specific features required.

= 13. Cisco Meraki

* Start your free demo today 

= 14. AirDroid Business

* Try AirDroid Business for 14 Days Free Trial

= 15. SOTI MobiControl

* Begin Your 30-Day Free Trial of the
* SOTI ONE Platform

= 16. IBM MaaS360:

* 30 days free trial.

= 17. Headwind 

 * $19.90 / year per device
 * No server expenses
 * Pay for your devices only
 * Full-featured system
 * Expedited technical support

= 18. Citrix Endpoint Management 

* Pricing often scales based on the number of devices that need to be managed. The more devices you have, the more expensive the subscription might be.

= 19. MicroMDM

* MicroMDM is an open-source MDM solution primarily targeted at Apple devices,

= 20. AirWatch

* starts at $4.33 per device/month

= 21.Google's Android Enterprise

* Typical prices range from about $4 to $9 per device per month, depending on the features and scale needed.

= 22.FleetMD

* FleetMD Free Plan typically supports a smaller number of devices. For example, some device management services offer free plans for up to 10 or 20 devices. If you want to manage 50 devices, you might be required to upgrade to a paid plan, as the free tier may not support this many devices.

= 23. Trend Micro

* 30 days free trial :(

= 24. SimpleMDM

* Create a SimpleMDM account to start your free 30-day trial.

= 25. DriveStrike

* If devices 1 to 20 price is $2/per device.

= 26. SureMDM

* $3.99/month
Per Device

= 27. Moki Total Control

* Fill out the form to get started with a free trial of Moki’s groundbreaking customer-facing, single-purpose devices.

= 28. Awingu 

* $90 Per Concurrent User, Per Year

= 29. GoTo Resolve  

* Starting Price: $69 Per Month

= 30 WipeDrive

* $19.95/one-time/drive

= 31.LimaxLock MDM

* Free 14-day trial

= 32. TinyMDM 

* Test our MDM solution for 30 days, then subscribe to one of TinyMDM pricing plans (USD). 

= 33. Esper

* Genesis(cheapest plan) $2 per device/month

= 34. Zelt

* After free trial -> Core plan(cheapest one)  $5 per seat per month

= 35. Cortado MDM

* USD 7.50

= 36. EasyControl MDM

* EasyControl MDM has a free version and offers a free trial. EasyControl MDM paid version starts at US$12.00/year. 

= 37. Mambo

* Price per device / month $0.99

= 38. GridMDM

* Starting from 2/user

= 39. VantageMDM

* Starting from: $0.99/month





